### ISSUE TITLE
Fix code scanning alert - DemoApplication

### ISSUE THREAD

**Issue by michaellambgelo** [michaellambgelo/demo#4]
Tracking issue for:
- [x] https://github.com/michaellambgelo/demo/security/code-scanning/1

**Comment by fornclakess** [comment]
Can you please assign me this? I can work on it.

**Comment by michaellambgelo** [comment]
Thanks for taking this one @fornclakess 

I accepted and merged PR #5

As we discussed in our pair programming session, this PR doesn't solve the root cause of the XSS vulnerability.

Let's create a `Hello.java` class with a single variable `String name` in the `model` package, similar to how the `/greeting` endpoint works. This should be more in-line with access safety. 

Ping me on Discord if you run into any blockers.

**Comment by fornclakess** [comment]
Will do
