### ISSUE TITLE
Implement Other File Formats

### ISSUE THREAD

**Issue by michaellambgelo** [michaellambgelo/demo#6]
In `ImageService` interface there are methods listed for supporting the conversion of an SVG to a JPEG. 

Add new methods in [ImageServiceImpl](https://github.com/michaellambgelo/demo/blob/master/src/main/java/dev/michaellamb/demo/service/impl/ImageServiceImpl.java) to support transcoding SVG to other image formats available using the Apache Batik Transcoder module (PNG, TIFF).

For more info see https://xmlgraphics.apache.org/batik/using/transcoder.html

**Comment by parikshitsm** [comment]
Sure @michaellambgelo  - I will work on this. Thanks.

**Comment by michaellambgelo** [comment]
This issue is closed! No plans to integrate a TIFF conversion in the image-controller
